spring:
  jackson:
    date-format: yyyy/MM/dd
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cpictool?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: yang0729
    driver-class-name: com.mysql.cj.jdbc.Driver
# MyBatis配置
mybatis:
  # 搜索指定包别名
  type-aliases-package: com.yang.**
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 加载全局的配置文件
  config-location: classpath:mybatis/mybatis-config.xml

person:
  username: 张洋
  age: 24
  boos: true
  birth: 1998/07/29
  pet:
    name: 当当
    age: 8
  interests: [篮球,足球,棒球]
  animal:
    - 狮子
    - 老虎
    - 雪豹
  score:
    yuwen: 100
    shuxue: 99
    english: 60
  salary: [8888.88,12000.99]
  all-pets:
    sick:
      - {name: 美国,age: 250}
      - {name: 英国,age: 500}
    health:
      - {name: 中国,age: 5000}
      - {name: 俄罗斯,age: 800}








