spring:
#  mvc:
#    static-path-pattern: /super/**

  web:
    resources:
      #改了以后就只有这一个路径下的可以访问了
      static-locations: classpath:/xixi/
      #默认是true,设置为FALSE可以禁用所有的静态资源
      add-mappings: true
  #开启rest风格就是将hiddenFilter给打开
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql:///jinshouzhi
    username: root
    password: yang0729
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      aop-patterns: com.atguigu.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false